import { ClerkProvider } from '@clerk/nextjs';
import "@uploadthing/react/styles.css";
import "~/styles/globals.css";

import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin';
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { extractRouterConfig } from 'uploadthing/server';
import TopNav from "./_components/TopNav";
import { ourFileRouter } from './api/uploadthing/core';

export const metadata: Metadata = {
  title: "Lean Gallery",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable} flex-col flex gap-4`}>
        <NextSSRPlugin

          /**
           * The `extractRouterConfig` will extract **only** the route configs
           * from the router to prevent additional information from being

           * leaked to the client. The data passed to the client is the same
           * as if you were to fetch `/api/uploadthing` directly.
           */
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
        <body>
          <TopNav />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
